# Generated by Django 3.2 on 2021-05-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('is_moderator', 'Модератор')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
